---
title: "log_log_PNC_group_normative"
author: "Kevin Sun"
date: "`10/31/2025`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gifti)
library(RNifti)
library(ciftiTools)
ciftiTools.setOption('wb_path', '/workbench')
library(ggplot2)
library(dplyr)
library(readr)
library(sjPlot)
library(mgcv)
```

#Import areas and demographics, normalize age
```{r}

PNC_TC_and_group_network_areas <- read.csv("../Results/summary.csv")
colnames(PNC_TC_and_group_network_areas)[1] <- "participant_id"

PNC_demographics <- read_tsv("../../PNC_data/study-PNC_desc-participants.tsv")
PNC_T1_qc <- read_tsv("../../PNC_data/study-PNC_desc-T1_qc.tsv")

PNC_areas_demos <- merge(PNC_TC_and_group_network_areas,PNC_demographics,by="participant_id")
PNC_all <- merge(PNC_areas_demos,PNC_T1_qc,by="participant_id")

```

## log-log models including age spline
```{r}
dout <- "../Results/PNC_group_net_areas_log-log_age_cov"
dir.create(dout)

summary(gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN1_gam<-gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN1_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN1"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN1_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN2_gam<-gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN2_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN2"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN2_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN3_gam<-gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN3_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN3"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN3_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN4_gam<-gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN4_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN4"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN4_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN5_gam<-gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN5_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN5"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN5_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN6_gam<-gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN6_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN6"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN6_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN7_gam<-gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN7_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN7"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN7_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN8_gam<-gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN8_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN8"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN8_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN9_gam<-gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN9_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN9"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN9_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN10_gam<-gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN10_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN10"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN10_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN11_gam<-gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN11_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN11"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN11_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN12_gam<-gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN12_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN12"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN12_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN13_gam<-gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN13_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN13"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN13_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN14_gam<-gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN14_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN14"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN14_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN15_gam<-gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN15_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN15"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN15_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN16_gam<-gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN16_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN16"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN16_area_TC_area_age_cov.doc", sep = ""))

summary(gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all))
PFN17_gam<-gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler+s(age),data=PNC_all)
tab_model(PFN17_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("log PFN17"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN17_area_TC_area_age_cov.doc", sep = ""))

```


```{r}
library(gratia)

draw(PFN1_gam)
draw(PFN2_gam)
draw(PFN3_gam)
draw(PFN4_gam)
draw(PFN5_gam)
draw(PFN6_gam)
draw(PFN7_gam)
draw(PFN8_gam)
draw(PFN9_gam)
draw(PFN10_gam)
draw(PFN11_gam)
draw(PFN12_gam)
draw(PFN13_gam)
draw(PFN14_gam)
draw(PFN15_gam)
draw(PFN16_gam)
draw(PFN17_gam)


```

## log-log models no age spline
```{r}
dout <- "../Results/PNC_group_net_areas_log-log"
dir.create(dout)

summary(gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN1_lm<-gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN1_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN1"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN1_area_TC_area.doc", sep = ""))

summary(gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN2_lm<-gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN2_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN2"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN2_area_TC_area.doc", sep = ""))

summary(gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN3_lm<-gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN3_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN3"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN3_area_TC_area.doc", sep = ""))

summary(gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN4_lm<-gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN4_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN4"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN4_area_TC_area.doc", sep = ""))

summary(gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN5_lm<-gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN5_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN5"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN5_area_TC_area.doc", sep = ""))

summary(gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN6_lm<-gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN6_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN6"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN6_area_TC_area.doc", sep = ""))

summary(gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN7_lm<-gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN7_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN7"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN7_area_TC_area.doc", sep = ""))

summary(gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN8_lm<-gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN8_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN8"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN8_area_TC_area.doc", sep = ""))

summary(gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN9_lm<-gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN9_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN9"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN9_area_TC_area.doc", sep = ""))

summary(gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN10_lm<-gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN10_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN10"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN10_area_TC_area.doc", sep = ""))

summary(gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN11_lm<-gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN11_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN11"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN11_area_TC_area.doc", sep = ""))

summary(gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN12_lm<-gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN12_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN12"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN12_area_TC_area.doc", sep = ""))

summary(gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN13_lm<-gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN13_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN13"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN13_area_TC_area.doc", sep = ""))

summary(gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN14_lm<-gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN14_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN14"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN14_area_TC_area.doc", sep = ""))

summary(gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN15_lm<-gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN15_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN15"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN15_area_TC_area.doc", sep = ""))

summary(gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN16_lm<-gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN16_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN16"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN16_area_TC_area.doc", sep = ""))

summary(gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all))
PFN17_lm<-gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler,data=PNC_all)
tab_model(PFN17_lm,pred.labels = c("Intercept","log TC Area","Sex","Euler Number"),dv.labels=c("log PFN17"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN17_area_TC_area.doc", sep = ""))

```

```{r}

anova_PFN1 <- anova(PFN1_lm, PFN1_gam, test = "Chisq")
anova_PFN2 <- anova(PFN2_lm, PFN2_gam, test = "Chisq")
anova_PFN3 <- anova(PFN3_lm, PFN3_gam, test = "Chisq")
anova_PFN4 <- anova(PFN4_lm, PFN4_gam, test = "Chisq")
anova_PFN5 <- anova(PFN5_lm, PFN5_gam, test = "Chisq")
anova_PFN6 <- anova(PFN6_lm, PFN6_gam, test = "Chisq")
anova_PFN7 <- anova(PFN7_lm, PFN7_gam, test = "Chisq")
anova_PFN8 <- anova(PFN8_lm, PFN8_gam, test = "Chisq")
anova_PFN9 <- anova(PFN9_lm, PFN9_gam, test = "Chisq")
anova_PFN10 <- anova(PFN10_lm, PFN10_gam, test = "Chisq")
anova_PFN11 <- anova(PFN11_lm, PFN11_gam, test = "Chisq")
anova_PFN12 <- anova(PFN12_lm, PFN12_gam, test = "Chisq")
anova_PFN13 <- anova(PFN13_lm, PFN13_gam, test = "Chisq")
anova_PFN14 <- anova(PFN14_lm, PFN14_gam, test = "Chisq")
anova_PFN15 <- anova(PFN15_lm, PFN15_gam, test = "Chisq")
anova_PFN16 <- anova(PFN16_lm, PFN16_gam, test = "Chisq")
anova_PFN17 <- anova(PFN17_lm, PFN17_gam, test = "Chisq")

pvals <- c(anova_PFN1$'Pr(>Chi'[2],
           anova_PFN2$'Pr(>Chi'[2],
           anova_PFN3$'Pr(>Chi'[2],
           anova_PFN4$'Pr(>Chi'[2],
           anova_PFN5$'Pr(>Chi'[2],
           anova_PFN6$'Pr(>Chi'[2],
           anova_PFN7$'Pr(>Chi'[2],
           anova_PFN8$'Pr(>Chi'[2],
           anova_PFN9$'Pr(>Chi'[2],
           anova_PFN10$'Pr(>Chi'[2],
           anova_PFN11$'Pr(>Chi'[2],
           anova_PFN12$'Pr(>Chi'[2],
           anova_PFN13$'Pr(>Chi'[2],
           anova_PFN14$'Pr(>Chi'[2],
           anova_PFN15$'Pr(>Chi'[2],
           anova_PFN16$'Pr(>Chi'[2],
           anova_PFN17$'Pr(>Chi'[2]
           )
pvals_fdr <- p.adjust(pvals, method = "fdr")
pvals <- data.frame(pvals)
pvals_fdr <- data.frame(pvals_fdr)
PFNs <- c("PFN1","PFN2","PFN3","PFN4","PFN5","PFN6","PFN7","PFN8","PFN9","PFN10","PFN11","PFN12","PFN13","PFN14","PFN15","PFN16","PFN17")
pvals_fdr <- cbind(PFNs, pvals_fdr)
write_csv(pvals_fdr,paste0(dout,"/PNC_group_norm_area_age_affect_pvals.csv"))

dout <- "../Results/PNC_group_net_areas_log-log_age_cov"
dir.create(dout)

tab_model(PFN1_lm,PFN1_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN1_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN2_lm,PFN2_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN2_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN3_lm,PFN3_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN3_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN4_lm,PFN4_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN4_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN5_lm,PFN5_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN5_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN6_lm,PFN6_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN6_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN7_lm,PFN7_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN7_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN8_lm,PFN8_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN8_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN9_lm,PFN9_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN9_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN10_lm,PFN10_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN10_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN11_lm,PFN11_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN11_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN12_lm,PFN12_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN12_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN13_lm,PFN13_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN13_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN14_lm,PFN14_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN14_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN15_lm,PFN15_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN15_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN16_lm,PFN16_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN16_area_TC_area_s(age)_comparison.doc", sep = ""))

tab_model(PFN17_lm,PFN17_gam,pred.labels = c("Intercept","log TC Area","Sex","Euler Number","Age Spline"),dv.labels=c("Model without Age", "Model with s(Age)"),digits=2,digits.p=2,show.se=TRUE,show.stat=TRUE,string.stat = "t",string.se = "Std. Error",show.intercept=TRUE,show.ci = FALSE, p.adjust="none",p.style="scientific", file = paste(dout,"/log-log_Group_PFN17_area_TC_area_s(age)_comparison.doc", sep = ""))


```