---
title: "Plotting_log_scatterplots"
author: "Kevin Sun"
date: "`10/31/2025`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(sjPlot)
library(mgcv)
```

#Import areas and demographics
```{r}
PNC_TC_and_group_network_areas <- read.csv("../../Inputs/PNC_summary_group.csv") # n = 1598
colnames(PNC_TC_and_group_network_areas)[1] <- "participant_id"

PNC_TC_and_PFNs_network_areas <- read.csv("../../Inputs/PNC_summary_PFNs.csv") # n = 1482
colnames(PNC_TC_and_PFNs_network_areas)[1] <- "participant_id"
colnames(PNC_TC_and_PFNs_network_areas)[3] <- "PFN1_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[4] <- "PFN2_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[5] <- "PFN3_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[6] <- "PFN4_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[7] <- "PFN5_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[8] <- "PFN6_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[9] <- "PFN7_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[10] <- "PFN8_soft_parcel_normed"
colnames(PNC_TC_and_PFNs_network_areas)[11] <- "PFN9_soft_parcel_normed"

PNC_demos <- read.csv("../../Inputs/filtered_demo_PNC.csv") #n = 1332

PNC_Group <- merge(PNC_TC_and_group_network_areas,PNC_demos,by="participant_id") # n = 1332
PNC_PFNs <- merge(PNC_TC_and_PFNs_network_areas,PNC_demos,by="participant_id") # n = 1332

#Check equivalence of TC areas
TC_area_equivalence <- identical(PNC_Group$TC_area, PNC_PFNs$TC_area)

```

## Fit models for PFNs and group atlas
```{r}
PNC_Group$sex<- factor(PNC_Group$sex)
PNC_PFNs$sex<- factor(PNC_PFNs$sex)

Group_PFN1_gam<-gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN2_gam<-gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN3_gam<-gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN4_gam<-gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN5_gam<-gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN6_gam<-gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN7_gam<-gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN8_gam<-gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN9_gam<-gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN10_gam<-gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN11_gam<-gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN12_gam<-gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN13_gam<-gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN14_gam<-gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN15_gam<-gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN16_gam<-gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")
Group_PFN17_gam<-gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_Group, method = "REML")

PFN1_gam<-gam(log(PFN1_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN2_gam<-gam(log(PFN2_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN3_gam<-gam(log(PFN3_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN4_gam<-gam(log(PFN4_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN5_gam<-gam(log(PFN5_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN6_gam<-gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN7_gam<-gam(log(PFN7_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN8_gam<-gam(log(PFN8_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN9_gam<-gam(log(PFN9_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN10_gam<-gam(log(PFN10_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN11_gam<-gam(log(PFN11_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN12_gam<-gam(log(PFN12_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN13_gam<-gam(log(PFN13_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN14_gam<-gam(log(PFN14_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN15_gam<-gam(log(PFN15_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN16_gam<-gam(log(PFN16_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
PFN17_gam<-gam(log(PFN17_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+s(age,k=4),data=PNC_PFNs, method = "REML")
```

## --- log-log --- ##
## Plot model-adjusted predictions on log-log scale (includes CIs) for PFNs and group atlas- anchored to isometry line and cropped to model line
```{r}
dout_PFN <- "../../Results/Scatterplots/PNC_PFN_power_laws"
dout_group <- "../../Results/Scatterplots/PNC_Group_power_laws"
dir.create(dout_PFN)
dir.create(dout_group)
library(ggeffects)
library(scales)

net_colors <- c("#E76178", "#7499C2", "#F5BA2E", "#7499C2", "#00A131",
                "#AF33AD", "#E443FF", "#E76178", "#E443FF", "#AF33AD",
                "#7499C2", "#E76178", "#7499C2", "#00A131", "#F5BA2E", 
                "#4E31A8", "#F5BA2E")


for (net in c(1:17)) {

# --- PFNs ---
  adj_net_area_pred <- ggpredict(get(paste0("PFN",net,"_gam")), terms = "TC_area", typical = "marginalmeans", back_transform = FALSE, ) #get adjusted prediction
  net_y_var <- paste0("PFN",net,"_soft_parcel_normed")

  TC_min <- min(adj_net_area_pred$x) # min TC area value in dataset
  net_0 <- adj_net_area_pred$predicted[adj_net_area_pred$x == TC_min] #get model-predicted proportion (cov-controlled) at minimum TC area
  #a_0 <- net_0/TC_min # No longer back-transforming predictions
  #intercept_0 <- log(a_0)
  
  intercept_0 <- net_0 - log(TC_min) # Get intercept of isometry line (log(Y) - log(X))
  
  # -----------------------------
  # Crop display window around the model-predicted fit line, not around the full raw point cloud.
  # -----------------------------
  fit_pad_frac <- 0.05
  
  pred_x_min <- min(log(adj_net_area_pred$x), na.rm = TRUE)
  pred_x_max <- max(log(adj_net_area_pred$x), na.rm = TRUE)
  
  fit_y_min <- min(
    adj_net_area_pred$predicted,
    adj_net_area_pred$conf.low,
    na.rm = TRUE
  )
  
  fit_y_max <- max(
    adj_net_area_pred$predicted,
    adj_net_area_pred$conf.high,
    na.rm = TRUE
  )
  
  x_required_range <- pred_x_max - pred_x_min
  y_required_range <- fit_y_max - fit_y_min
  
  plot_range <- max(x_required_range, y_required_range)
  
  plot_range <- plot_range * (1 + 2 * fit_pad_frac)
  
  x_center <- mean(c(pred_x_min, pred_x_max))
  y_center <- mean(c(fit_y_min, fit_y_max))
  
  x_min <- x_center - plot_range / 2
  x_max <- x_center + plot_range / 2
  
  y_min <- y_center - plot_range / 2
  y_max <- y_center + plot_range / 2
  
  Fig <- ggplot(adj_net_area_pred, aes(x = log(x), y = predicted)) +
    geom_point(data = PNC_PFNs, aes(x = log(TC_area), y = log(get(net_y_var))), size = 1, alpha = 0.4, color = net_colors[net]) +
    geom_abline(intercept = intercept_0, slope = 1, color = "#474747", linewidth = 0.75, alpha = 0.9, linetype = "longdash") + # isometry line
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = net_colors[net], alpha = 0.4) +
    geom_line() + #line based on adjusted prediction
    labs(
           # title = paste0("PFN"),
           # x = "log(Total Cortical Area)",
           # y = paste0("log(Network ",net," Area)"))+
           title = NULL,
           x = NULL,
           y =  NULL)+
    theme_classic() +
    theme(
        plot.title = element_text(size = 25, hjust = 0.5),
        axis.text.x = element_text(size = 44.75, color = "black"),
        axis.text.y = element_text(size = 44.75, color = "black"),
        axis.title.x  = element_text(size = 1),
        axis.title.y  = element_text(size = 1)
    ) +
    coord_cartesian(xlim = c(x_min, x_max), ylim = c(y_min, y_max), clip = "on") + # set axes limits to get isometry line at diagonal
    # Limits x and y axis to 1 decimal place
    #scale_x_continuous(breaks = c(11.7,11.9,12.1,12.3)) # Comment out for networks 14 and 15
    #scale_y_continuous(breaks = c(9.50,9.70,9.90)) # Comment in for network 9
    #scale_x_continuous(breaks = c(11.7,12.0,12.3)) + # Comment in for network 14
    #scale_y_continuous(breaks = c(8.6,8.8,9.0,9.2,9.4)) # Comment in for network 14
    #scale_y_continuous(labels = label_number(accuracy = 0.01))
    #theme(plot.margin = margin(10, 10, 10, 10))
  print(Fig)
  ggsave(paste0(dout_PFN,"/PNC_PFNs_PFN",net,"_adj_log_log_scatterplot_isometric_diag_anchored.png"), width = 18.5, height = 16, dpi = 600, units = "cm")
  ggsave(paste0(dout_PFN,"/PNC_PFNs_PFN",net,"_adj_log_log_scatterplot_isometric_diag_anchored.pdf"), device = cairo_pdf, width = 18.5, height = 16, dpi = 600, units = "cm")
  
# --- GROUP ATLAS ---
  adj_net_area_pred <- ggpredict(get(paste0("Group_PFN",net,"_gam")), terms = "TC_area", typical = "marginalmeans", back_transform = FALSE, ) #get adjusted prediction
  net_y_var <- paste0("PFN",net,"_soft_parcel_normed")

  TC_min <- min(adj_net_area_pred$x) # min TC area value in dataset
  net_0 <- adj_net_area_pred$predicted[adj_net_area_pred$x == TC_min] #get model-predicted proportion (cov-controlled) at minimum TC area
  #a_0 <- net_0/TC_min # No longer back-transforming predictions
  #intercept_0 <- log(a_0)
  
  intercept_0 <- net_0 - log(TC_min) # Get intercept of isometry line (log(Y) - log(X))
  
  # -----------------------------
  # Crop display window around the model-predicted fit line, not around the full raw point cloud.
  # -----------------------------
  fit_pad_frac <- 0.05
  
  pred_x_min <- min(log(adj_net_area_pred$x), na.rm = TRUE)
  pred_x_max <- max(log(adj_net_area_pred$x), na.rm = TRUE)
  
  fit_y_min <- min(
    adj_net_area_pred$predicted,
    adj_net_area_pred$conf.low,
    na.rm = TRUE
  )
  
  fit_y_max <- max(
    adj_net_area_pred$predicted,
    adj_net_area_pred$conf.high,
    na.rm = TRUE
  )
  
  x_required_range <- pred_x_max - pred_x_min
  y_required_range <- fit_y_max - fit_y_min
  
  plot_range <- max(x_required_range, y_required_range)
  
  plot_range <- plot_range * (1 + 2 * fit_pad_frac)
  
  x_center <- mean(c(pred_x_min, pred_x_max))
  y_center <- mean(c(fit_y_min, fit_y_max))
  
  x_min <- x_center - plot_range / 2
  x_max <- x_center + plot_range / 2
  
  y_min <- y_center - plot_range / 2
  y_max <- y_center + plot_range / 2
  
  Fig <- ggplot(adj_net_area_pred, aes(x = log(x), y = predicted)) +
    geom_point(data = PNC_Group, aes(x = log(TC_area), y = log(get(net_y_var))), size = 1, alpha = 0.4, color = net_colors[net]) +
    geom_abline(intercept = intercept_0, slope = 1, color = "#474747", linewidth = 0.75, alpha = 0.9, linetype = "longdash") + # isometry line
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = net_colors[net], alpha = 0.4) +
    geom_line() + #line based on adjusted prediction
    labs(
           # title = paste0("Group Atlas"),
           # x = "log(Total Cortical Area)",
           # y = paste0("log(Network ",net," Area)"))+
           title = NULL,
           x = NULL,
           y =  NULL)+
    theme_classic() +
    theme(
        plot.title = element_text(size = 25, hjust = 0.5),
        axis.text.x = element_text(size = 44.75, color = "black"),
        axis.text.y = element_text(size = 44.75, color = "black"),
        axis.title.x  = element_text(size = 1),
        axis.title.y  = element_text(size = 1)
    ) +
    coord_cartesian(xlim = c(x_min, x_max), ylim = c(y_min, y_max), clip = "on") + # set axes limits to get isometry line at diagonal (based on PFN isometry line, consistent axes)
    # Limits x and y axis to 1 decimal place
    scale_x_continuous(breaks = c(11.7,11.9,12.1,12.3,12.5))
    #scale_y_continuous(labels = label_number(accuracy = 0.01))
    #theme(plot.margin = margin(10, 10, 10, 10))
  print(Fig)
  ggsave(paste0(dout_group,"/PNC_Group_PFN",net,"_adj_log_log_scatterplot_isometric_diag_anchored.png"), width = 18.5, height = 16, dpi = 600, units = "cm")
  ggsave(paste0(dout_group,"/PNC_Group_PFN",net,"_adj_log_log_scatterplot_isometric_diag_anchored.pdf"), device = cairo_pdf, width = 18.5, height = 16, dpi = 600, units = "cm")
}
```

## --- log-log --- ##
## PFN 6, sex-specific ##
## Plot model-adjusted predictions on log-log scale (includes CIs) for PFNs and group atlas- anchored isometry line + diag
```{r}
dout_PFN <- "../../Results/Scatterplots/PNC_PFN_power_laws"
dout_group <- "../../Results/Scatterplots/PNC_Group_power_laws"
dir.create(dout_PFN)
dir.create(dout_group)
library(ggeffects)

PFN6_gam_sex_mod<-gam(log(PFN6_soft_parcel_normed)~log(TC_area)+sex+euler+median_fd_combined+log(TC_area)*sex+s(age,k=4),data=PNC_PFNs)

net = 6

net_colors <- c("#E76178", "#7499C2", "#F5BA2E", "#7499C2", "#00A131",
                "#AF33AD", "#E443FF", "#E76178", "#E443FF", "#AF33AD",
                "#7499C2", "#E76178", "#7499C2", "#00A131", "#F5BA2E", 
                "#4E31A8", "#F5BA2E")

#--- LOG-LOG ---
adj_net_area_pred <- ggpredict(PFN6_gam_sex_mod, terms = c("TC_area","sex"), back_transform = FALSE, ) #get adjusted prediction
net_y_var <- paste0("PFN",net,"_soft_parcel_normed")

TC_min <- min(adj_net_area_pred$x) # min TC area value in dataset
net_0 <- adj_net_area_pred$predicted[adj_net_area_pred$x == TC_min] #get model-predicted proportion (cov-controlled) at minimum TC area
intercept_0 <- net_0 - log(TC_min) # Get intercept of isometry line (log(Y) - log(X))

# raw data limits on log scale
y_min <- min(log(PNC_PFNs[net_y_var]))
y_max <- max(log(PNC_PFNs[net_y_var]))

# setting axes limits to get standardized angle of isometric line, line will span panel diagonally
x_min <- y_min - intercept_0 
x_max <- y_max - intercept_0
  
for (sex_var in c("Female","Male")) {
  if (sex_var == "Female") {pred_idx = 1} else {pred_idx = 2}
  Fig <- ggplot(adj_net_area_pred[adj_net_area_pred$group == sex_var,], aes(x = log(x), y = predicted)) +
    geom_point(data = PNC_PFNs[PNC_PFNs$sex == sex_var,], aes(x = log(TC_area), y = log(get(net_y_var))), size = 1, alpha = 0.4, color = net_colors[net]) +
    geom_abline(intercept = intercept_0[pred_idx], slope = 1, color = "#474747", linewidth = 0.75, alpha = 0.9, linetype = "longdash") + # isometry line
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = net_colors[net], alpha = 0.4) +
    geom_line() + #line based on adjusted prediction
    labs(title = paste0("PFN Network ",net," Scaling in PNC, ",sex_var),
           x = "log(Total Cortical Area)",
           y = paste0("log(Network ",net," Area)")) +
    theme_classic() +
    theme(
        plot.title = element_text(size = 25, hjust = 0.5),
        axis.text.x = element_text(size = 25, color = "black"),
        axis.text.y = element_text(size = 25, color = "black"),
        axis.title.x  = element_text(size = 25, margin = margin(t = 10)),
        axis.title.y  = element_text(size = 25, margin = margin(r = 10))
    ) +
    coord_cartesian(xlim = c(x_min[pred_idx], x_max[pred_idx]), ylim = c(y_min, y_max), clip = "off") + # set axes limits to get isometry line at diagonal
    #scale_x_continuous(breaks = c(11.5, 11.75, 12, 12.25, 12.5, 12.75)) +
    theme(plot.margin = margin(20, 20, 20, 20))
  print(Fig)
  ggsave(paste0(dout_PFN,"/PNC_PFNs_PFN",net,"_",sex_var,"_adj_log_log_scatterplot_isometric_diag_anchored.png"), width = 19, height = 16, dpi = 600, units = "cm")
}

#--- RAW ---
adj_net_area_pred_raw <- ggpredict(PFN6_gam_sex_mod, terms = c("TC_area","sex"), back_transform = TRUE, ) #get adjusted prediction
net_y_var <- paste0("PFN",net,"_soft_parcel_normed")

TC_min <- min(adj_net_area_pred_raw$x) # min TC area value in dataset
net_0 <- adj_net_area_pred_raw$predicted[adj_net_area_pred_raw$x == TC_min]
a_0 <- net_0/TC_min #get model-predicted proportion (cov-controlled) at minimum TC area
intercept_0 <- log(a_0)

y_min <- min(log(PNC_PFNs[net_y_var]))
y_max <- max(log(PNC_PFNs[net_y_var]))

x_min <- y_min - intercept_0 #setting axes limits to get standardized angle of isometric line
x_max <- y_max - intercept_0
  
for (sex_var in c("Female","Male")) {
  if (sex_var == "Female") {pred_idx = 1} else {pred_idx = 2}
  Fig <- ggplot(adj_net_area_pred_raw[adj_net_area_pred_raw$group == sex_var,], aes(x = x, y = predicted)) +
  geom_point(data = PNC_PFNs[PNC_PFNs$sex == sex_var,], aes(x = TC_area, y = get(net_y_var)), size = 2, alpha = 0.4, color = net_colors[net]) +
  geom_abline(intercept = 0, slope = a_0[pred_idx], color = "#474747", linewidth = 0.75, alpha = 0.9, , linetype = "longdash") + # isometry line
  #geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = net_colors[net], alpha = 0.4) + # CI not interpretable on raw scale
  geom_line(color = net_colors[net], linewidth = 1.2) + #line based on adjusted prediction
  labs(title = paste0("PFN Network ",net," Scaling in PNC, ",sex_var),
         x = expression("Total Cortical Area ("~mm^{2}~")"),
         y = bquote("Network " * .(net) * " Area ("~mm^2~")")) +
  theme_classic() +
  theme(
      plot.title = element_text(size = 25, hjust = 1),
      axis.text.x = element_text(size = 25, color = "black"),
      axis.text.y = element_text(size = 25, color = "black"),
      axis.title  = element_text(size = 25)
  )
  print(Fig)
  ggsave(paste0(dout_PFN,"/PNC_PFNs_PFN",net,"_",sex_var,"_adj_raw_scatterplot_anchored.png"), width = 19, height = 16, dpi = 600, units = "cm")
}
```
